// Popular board and card games. Player counts, times and ages are approximate (from typical box info), so check
// the box for your edition. "about" describes the feel of the game; the AI matches your words against it.
export const GAMES = [
  { name: "Catan", emoji: "🐑", min: 3, max: 4, minutes: 90, age: "10+", type: "strategy, trading", about: "Build settlements and trade resources with friends. Lots of negotiation and a bit of luck. A modern classic." },
  { name: "Ticket to Ride", emoji: "🚂", min: 2, max: 5, minutes: 60, age: "8+", type: "family strategy", about: "Collect colorful train cards and claim railway routes across a map. Easy to learn, great for families." },
  { name: "Carcassonne", emoji: "🏰", min: 2, max: 5, minutes: 40, age: "7+", type: "tile-laying", about: "Place tiles to build a medieval landscape of cities, roads and fields. Calm, clever and easy to teach." },
  { name: "Pandemic", emoji: "🦠", min: 2, max: 4, minutes: 45, age: "8+", type: "cooperative", about: "Work together as a team to stop diseases spreading around the world. Everyone wins or loses together." },
  { name: "Codenames", emoji: "🕵️", min: 4, max: 8, minutes: 15, age: "10+", type: "party, word game", about: "Two teams give one-word clues to find their secret agents. Fun party word game for groups." },
  { name: "Azul", emoji: "🟦", min: 2, max: 4, minutes: 40, age: "8+", type: "abstract, puzzle", about: "Draft beautiful tiles to decorate a palace wall. Pretty, relaxing and a little bit competitive." },
  { name: "Splendor", emoji: "💎", min: 2, max: 4, minutes: 30, age: "10+", type: "engine building", about: "Collect gems and buy cards to become the richest merchant. Simple rules, satisfying strategy." },
  { name: "7 Wonders", emoji: "🏛️", min: 3, max: 7, minutes: 30, age: "10+", type: "card drafting", about: "Build an ancient civilization by picking and passing cards. Plays fast even with many players." },
  { name: "Dixit", emoji: "🎨", min: 3, max: 8, minutes: 30, age: "8+", type: "party, creative", about: "Tell stories about dreamy, beautiful picture cards and guess each other's clues. Creative and relaxed." },
  { name: "Exploding Kittens", emoji: "🐱", min: 2, max: 5, minutes: 15, age: "7+", type: "card game, party", about: "Silly, fast card game about avoiding the exploding kitten. Lots of laughing and chaos." },
  { name: "UNO", emoji: "🃏", min: 2, max: 10, minutes: 30, age: "7+", type: "card game, family", about: "Classic card game of matching colors and numbers. Everyone knows it, perfect for all ages." },
  { name: "Monopoly", emoji: "🎩", min: 2, max: 8, minutes: 120, age: "8+", type: "family, trading", about: "Buy properties, build houses and bankrupt your friends. Long, classic family game with lots of luck." },
  { name: "Scrabble", emoji: "🔤", min: 2, max: 4, minutes: 90, age: "8+", type: "word game", about: "Build words on the board for points. Great for word lovers and quiet, thoughtful evenings." },
  { name: "Chess", emoji: "♟️", min: 2, max: 2, minutes: 45, age: "6+", type: "abstract strategy", about: "The classic two-player strategy game with no luck. Deep thinking and a lifetime to master." },
  { name: "Jenga", emoji: "🧱", min: 2, max: 8, minutes: 15, age: "6+", type: "dexterity, party", about: "Pull blocks from a wobbly tower without knocking it over. Tense, simple and fun for any group." },
  { name: "Kingdomino", emoji: "👑", min: 2, max: 4, minutes: 15, age: "8+", type: "family, tile-laying", about: "Build a little kingdom with domino tiles. Quick, cute and easy for kids and adults." },
  { name: "Sushi Go!", emoji: "🍣", min: 2, max: 5, minutes: 15, age: "8+", type: "card drafting, family", about: "Pick and pass cute sushi cards to make the best meal. Fast, adorable and easy to learn." },
  { name: "Love Letter", emoji: "💌", min: 2, max: 6, minutes: 20, age: "10+", type: "card game, deduction", about: "Tiny card game of bluffing and guessing with just a few cards. Great to carry anywhere." },
  { name: "The Crew", emoji: "🚀", min: 2, max: 5, minutes: 20, age: "10+", type: "cooperative card game", about: "Cooperative trick-taking space missions with limited talking. Clever teamwork puzzles." },
  { name: "Hanabi", emoji: "🎆", min: 2, max: 5, minutes: 25, age: "8+", type: "cooperative card game", about: "Build a fireworks show together, but you can't see your own cards. Teamwork and memory." },
  { name: "Forbidden Island", emoji: "🏝️", min: 2, max: 4, minutes: 30, age: "10+", type: "cooperative, family", about: "Work together to collect treasures before the island sinks. Great first co-op game for families." },
  { name: "Wingspan", emoji: "🐦", min: 1, max: 5, minutes: 60, age: "10+", type: "engine building", about: "Attract beautiful birds to your wildlife park. Relaxing, gorgeous strategy game, also plays solo." },
  { name: "Clue (Cluedo)", emoji: "🔍", min: 3, max: 6, minutes: 45, age: "8+", type: "deduction, family", about: "Solve the mystery of who did it, where and with what. Classic detective game." },
  { name: "Spot It! (Dobble)", emoji: "👀", min: 2, max: 8, minutes: 15, age: "6+", type: "speed, party", about: "Race to spot the matching symbol between two cards. Super quick and great for kids." },
  { name: "Telestrations", emoji: "✏️", min: 4, max: 8, minutes: 30, age: "12+", type: "party, drawing", about: "Drawing and guessing telephone game where messages get hilariously lost. Big laughs for groups." },
  { name: "Just One", emoji: "💡", min: 3, max: 7, minutes: 20, age: "8+", type: "cooperative party word game", about: "Everyone writes a one-word clue to help one player guess, but duplicate clues are cancelled. Friendly and fun." },
  { name: "Wavelength", emoji: "📡", min: 2, max: 12, minutes: 45, age: "14+", type: "party, team", about: "Guess where a clue falls on a scale like hot to cold. Sparks funny debates in big groups." },
  { name: "Skull", emoji: "💀", min: 3, max: 6, minutes: 30, age: "10+", type: "bluffing", about: "Pure bluffing game with just a few coasters. Tense, quick and great for reading your friends." },
  { name: "King of Tokyo", emoji: "🦖", min: 2, max: 6, minutes: 30, age: "8+", type: "dice, party", about: "Giant monsters roll dice and smash each other to rule Tokyo. Loud, lucky and very fun." },
  { name: "Patchwork", emoji: "🧵", min: 2, max: 2, minutes: 30, age: "8+", type: "two-player puzzle", about: "Build the coziest quilt from puzzle pieces. A calm, clever game for couples or two friends." },
  { name: "Jaipur", emoji: "🐫", min: 2, max: 2, minutes: 30, age: "12+", type: "two-player trading", about: "Trade goods and camels to become the richest merchant. Quick, tense duel for two." },
  { name: "Qwirkle", emoji: "🔷", min: 2, max: 4, minutes: 45, age: "6+", type: "abstract, family", about: "Match colors and shapes with tiles. Simple and relaxing, great for grandparents and kids together." },
  { name: "Blokus", emoji: "🟨", min: 2, max: 4, minutes: 20, age: "7+", type: "abstract strategy", about: "Place colorful pieces and block your opponents' space. Easy to learn, surprisingly strategic." },
  { name: "Mysterium", emoji: "👻", min: 2, max: 7, minutes: 45, age: "10+", type: "cooperative deduction", about: "A ghost gives dreamlike picture clues to help psychics solve a mystery. Spooky, creative co-op." },
  { name: "Dominion", emoji: "🗡️", min: 2, max: 4, minutes: 30, age: "13+", type: "deck building", about: "The original deck-building game. Buy cards to build a stronger deck and a bigger kingdom." },
  { name: "Terraforming Mars", emoji: "🪐", min: 1, max: 5, minutes: 120, age: "12+", type: "heavy strategy", about: "Turn Mars into a livable planet with science projects. Long, deep strategy for experienced gamers." },
  { name: "Gloomhaven", emoji: "⚔️", min: 1, max: 4, minutes: 120, age: "14+", type: "campaign, dungeon crawler", about: "Epic cooperative fantasy campaign with tactical battles. A huge game for dedicated groups." },
  { name: "Guess Who?", emoji: "🧑", min: 2, max: 2, minutes: 20, age: "6+", type: "deduction, kids", about: "Ask yes or no questions to guess the mystery person. Classic simple game for kids." },
  { name: "Connect Four", emoji: "🔴", min: 2, max: 2, minutes: 10, age: "6+", type: "abstract, kids", about: "Drop discs to get four in a row. Quick and easy for kids and anyone." },
  { name: "Bananagrams", emoji: "🍌", min: 1, max: 8, minutes: 15, age: "7+", type: "word game, speed", about: "Race to build your own crossword grid with letter tiles. Fast, portable word game." },
];
